### ISSUE TITLE
Missing/duplicated values in WATHTE timeseries and extremes (old waterwebservices)

### ISSUE THREAD

**Issue by veenstrajelmer** [Rijkswaterstaat/wm-ws-dl#39]
https://github.com/Rijkswaterstaat/wm-ws-dl/issues/38 describes missing extremes for some stations. Within the kenmerkendewaarden project there was a more extensive analysis carried out (station_list_tk, period 1870-01-01 to 2024-01-01). This is purely based on the `OphalenAantalWaarnemingen` feature of the DDL and [the code is available on github](https://github.com/Deltares-research/kenmerkendewaarden/blob/0e1ae9fc43d21159087459d3d057adb7bd45da95/examples/KWK_getcheckdata.py#L64-L84). This data was retrieved on 9-4-2024, so after the [corrections in DDL data on 22-02-2024](https://rijkswaterstaatdata.nl/waterdata/#hfd2f5e23-5092-4169-9f36-41e9734e7d87).

For extremes, we expect `4*365=1460` values for four-daily low/high extremes. More could indicate duplicates or aggers, less means missings. The same for timeseries, here we expect `24*365=8760` to `6*24*365=52560` values for 60min/10min interval. All stations with more values have duplicated data. Some stations cannot be retrieved per year, since the maximum allowed number of values by the DDL is 157681. Therefore, all stations have to be retrieved per month instead which is often quite inefficient.

These amounts are visualized with a relative coverage per year. For extremes:
![image](https://github.com/Rijkswaterstaat/wm-ws-dl/assets/60435591/7336e996-c8a0-478e-b006-8af36196cbf7)
Cases with more than 100% coverage like HOEKVHLD, can probably be explained by presence of aggers. However, for SCHEVNGN and STELLDBTN this is not consistent over time. There are also stations with no ext stations present at all (A12, AWGPFM, BAALHK, GATVBSLE, D15, F16, F3PFM, J6, K14PFM, L9PFM, MAASMSMPL, NORTHCMRT, OVLVHWT, Q1, SINTANLHVSGR, WALSODN), is this expected?

For timeseries:
![image](https://github.com/Rijkswaterstaat/wm-ws-dl/assets/60435591/8c0a0e43-5330-40b9-83e8-bc7d2f63638e)

Raw data csv's with the amount of measurements per year and per station:
[data_amount_ext.csv](https://github.com/Rijkswaterstaat/wm-ws-dl/files/14922222/data_amount_ext.csv)
[data_amount_ts.csv](https://github.com/Rijkswaterstaat/wm-ws-dl/files/14922223/data_amount_ts.csv)

**Additional issue**
The stations D15, J6 and NES only show very recent data, since for these stations accidentally the realtime instead of the historic station is selected. https://github.com/Rijkswaterstaat/wm-ws-dl/issues/20 would solve this issue.

**Comment by TvLoon-RWS** [comment]
This issue will be checked with the long-term data storage

**Comment by KDoekes-RWS** [comment]
This is all known and explainable. The number of HW/LW's in a normal year for a non-agger location is 1410 or 1411.
The series of course didn't all start on January 1st of a year, and there are als cases when during long times only HW's were available for a tide gauge (e.g. Cadzand) of only daylight HW/LW's (e.g. Oudeschild).
Equidistnat time series with too much or too little data cab not be stored in DONAR. There are some cases of storage of more than one series for the same period, with different time steps, such as 10 minutes and 1 minutes for the 'basisstations' (Vlissingen, Hoek van Holland, IJmuiden buitenhaven, Harlingen and Delfzijl) during the last years, and cases where more than one series for the same period with different manager codes (Dutch: instantiecodes) were toreed, mainly in the Delta area.
The data of a number of relatively new offshore gauges are not validated, and no HW/LW data are computed. The gauges in the Dekta area mentioned for which no extremes were computed at all are not considered part of the MWTL program, either.

**Comment by veenstrajelmer** [comment]
When retrieving the measurement amounts after December 2024 (e.g. today, 9-4-2025, including a fresh DDL catalog), we get the following status.

For extremes:
![Image](https://github.com/user-attachments/assets/439030ff-4182-4689-b9e1-fa3bec8081af)

For timeseries:
![Image](https://github.com/user-attachments/assets/5b72c136-c58c-46d3-be17-4e980bb8ea83)

Note that K13APFM was dropped because of https://github.com/Deltares-research/kenmerkendewaarden/issues/195.

Several duplicates for years 2000-2020 have been resolved. From 2022 onwards there are many duplicates added. This should be resolved, together with the remaining duplicates. Also many years are missing still.

@TvLoon-RWS reported the following on 12-2-2025 (based on answer by TC):
_De metingen zijn in deze gevallen dus hetzelfde, maar staan er onder meerdere OGI’s in. Dit komt in dit geval ook in Donar zo voor. 
Ton is hiervan op de hoogte, dit is een bekend probleem voor een aantal locaties en data na 1-1-2022. 
Met de jaarvalidatie van 2024 zal dit ook opgeschoond worden. Je overzichtelijke grafiek kan hier zeker bij helpen. Ik hoop dat deze opschoning dan mee komt met de volgende export van Donar naar de WaterWebservices die gepland staat rond juli/augustus van data van jaar 2022 tot en met 2024._

**Comment by veenstrajelmer** [comment]
@TvLoon-RWS not only data from 2022 onwards is duplicated. The problem is more extensive. There are four sub-problems linking to respecitive issues where the problematic timestamps are documented. I will not copy these here to make sure to have a single source of truth (that can be updated after each update of the DDL data).
- [x] many (almost-)duplicates from 2021 onwards. No dedicated issue, but in https://github.com/Deltares-research/kenmerkendewaarden/issues/191 I also had to exclude the year 2021 since all or most of the extreme data was duplicated there also (mostly exact same timestamps and values).
- [x] Furthermore, some stations have (exact) duplicated extremes for 2020-12-31 (https://github.com/Deltares-research/kenmerkendewaarden/issues/196). This is problematic for kenmerkendewaarden since the analysis will fail for these stations (we focus on 2000 to and inclusive 2020 there). Can this be resolved as soon as possible?
- [ ] There are almost-duplicates for older periods, that point to incorrect extremes: https://github.com/Deltares-research/kenmerkendewaarden/issues/191 (also reported with less detail in https://github.com/Rijkswaterstaat/wm-ws-dl/issues/43)
- [ ] some stations have 10-minute as well as hourly timeseries combined: https://github.com/Rijkswaterstaat/wm-ws-dl/issues/35 >> this is fixed on 7 August 2025 but it still occurs for other stations: https://github.com/Rijkswaterstaat/wm-ws-dl/issues/48
- [ ] many stations have duplicated time-value-combinations that can easily be filtered out but should be cleaned anyway: https://github.com/Rijkswaterstaat/wm-ws-dl/issues/49
- [ ] Stations with too little extremes in 20-year period of interest: https://github.com/Deltares-research/kenmerkendewaarden/issues/264 (based on new waterwebservices/ddapi20)

**Comment by veenstrajelmer** [comment]
When retrieving the measurement amounts on August 7/8 (7 for timeseries, 8 for extremes), including a fresh DDL catalog, we get the following status.

For extremes:
<img width="2800" height="1600" alt="Image" src="https://github.com/user-attachments/assets/d9315741-f0eb-454f-b151-24464b0816d6" />

For extremes:
- the duplicates in recent years are resolved
- there were some extremes for BAALHK for recent years, they have all disappeared. Most of the stations with missing extremes are located offshore or in Zeeland: https://github.com/Rijkswaterstaat/wm-ws-dl/issues/50
- for BROUWHVSGT08 there were previously more extremes for 2010 (100% coverage), they have disappeared (all of them)
- for WESTKPLE there were previously more extremes available in the period of 1880 to 1945
- there are many stations without extremes, is that expected? They cannot be derived from 10-min data (too coarse to include the peaks), but maybe some of the missing data is still available somewhere?

For timeseries:
<img width="2800" height="1600" alt="Image" src="https://github.com/user-attachments/assets/327e2a82-f05d-4e6c-8951-16decee4ec60" />

For timeseries:
- the duplicates in recent years are resolved
- the missing gap across many stations around 1980 is resolved
- there still seem to be some duplicates around 1980, but this has to be looked in further. The percentage/color is computed based on the median of the amount of measurements over all stations for that year. It could well be that some stations went from 60 to 10 minute interval before other stations did, which would then result in a 600% value. However, for these stations there are actual duplicates present as documented in https://github.com/Rijkswaterstaat/wm-ws-dl/issues/48 and https://github.com/Rijkswaterstaat/wm-ws-dl/issues/49
- there seems to be data missing with respect to the first coverage image for the period around 1975 for BROUWHVSGT02 and OOSTSDE04

Conclusion: the data availability has drastically improved, but there are some things that are worth looking into before closing this issue. Please also have a look at the issues linked in [the comment above](https://github.com/Rijkswaterstaat/wm-ws-dl/issues/39#issuecomment-2794368605) for some more detailed analyses.

**Comment by veenstrajelmer** [comment]
When retrieving the data from the new waterwebservices on 12-12-2024, we get the following figures.

For extremes:
<img width="2800" height="1600" alt="Image" src="https://github.com/user-attachments/assets/68ac9a38-375c-4d4e-8827-dce52055470e" />

For timeseries:
<img width="2800" height="1600" alt="Image" src="https://github.com/user-attachments/assets/bbe9659d-20f1-4d03-9c52-f5398a7e20e6" />

What has changed compared to the previous retrieval:
- measurement data for north.cormorant has disappeared, probably because it is not in the Netherlands and therefore not (yet?) on the whitelist
- many more extremes for: baalhoek, brouwershavenschegat, gatvanborselle, breskenshaven, holwerd (but also many duplicates), katsbuiten, marollegat, oosterschelde 4/11/14, Ossenisse/OVLVHWT, stellendambuiten, vlaktevanderaan, walsoorden, yerseke.
- duplicated timeseries data in 2024

This issue will be continued on the waterwebservices github page: https://github.com/Rijkswaterstaat/WaterWebservices/issues/22. There, the station order will be changed (made alphabetically).
